# The following configuration 
# configures k3s manually with the c3os configuration mechanism.

stages:     
   initramfs:
     - name: "Setup users"
      #  users:
      #   c3os:
      #     password: "c3os"
       authorized_keys:
        c3os: 
        - github:mudler
       commands:
       - passwd -l c3os

k3s:
  enabled: true