name: "Default persistency mode for k3s"
stages:
   initramfs:
     - if: '[ ! -f "/run/cos/recovery_mode" ]'
       name: "Persist k3s and kubelet into COS_PARTITION"
       commands:
       - |
            target=/usr/local/.c3os-state

            # Always want the latest update of systemd conf from the image
            # TODO: This might break the fallback system
            mkdir -p "${target}/etc/systemd/"
            rsync -av /etc/systemd/ "${target}/etc/systemd/"

            # Only populate ssh conf once
            if [ ! -e "${target}/etc/ssh" ]; then
              mkdir -p "${target}/etc/ssh/"
              rsync -av /etc/ssh/ "${target}/etc/ssh/"
            fi

            # undo /home /opt /root mount from cos immutable-rootfs module
            # TODO: we could think of configuring custom overlay paths in
            # immutable rootfs package. So this part could be omitted
            for i in home opt root; do
              sed -i "/overlay \/${i} /d" /etc/fstab
              nsenter -m -t 1 -- umount "/sysroot/${i}"
            done

            # setup directories as persistent
            # TODO: would it make sense defining persistent state overlayfs mounts
            # as part of the immutable rootfs config?
            for i in root opt home var/lib/rancher var/lib/kubelet etc/systemd etc/rancher etc/ssh; do
              mkdir -p "${target}/${i}" "/${i}"
              echo "${target}/${i} /${i} none defaults,bind 0 0" >> /etc/fstab
              nsenter -m -t 1 -- mount -o defaults,bind "/sysroot${target}/${i}" "/sysroot/${i}"
            done

            # ensure /var/log/journal exists so it's labeled correctly
            mkdir -p /var/log/journal            
