---
name: 'Test arm build'

on: 
 push:
 pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # OIDC support
    strategy:
      fail-fast: false
      matrix:
        include:
          - flavor: "opensuse-arm-rpi"
            dockerfile: "images/Dockerfile.opensuse-arm-rpi"
            platforms: "linux/arm64"
            model: rpi64
          # - flavor: "tumbleweed-arm-rpi"
          #   dockerfile: "Dockerfile.tumbleweed-arm-rpi"
          #   platforms: "linux/arm64"
          #   model: rpi64
          - flavor: "alpine-arm-rpi"
            dockerfile: "images/Dockerfile.alpine-arm-rpi"
            platforms: "linux/arm64"
            model: rpi64
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Build  🔧
        env:
          FLAVOR: ${{ matrix.flavor }}
          IMAGE: quay.io/c3os/c3os:${{ matrix.flavor }}-latest
          MODEL: ${{ matrix.model }}
        run: |
          export TAG=${GITHUB_REF##*/}
          IMAGE_NAME=c3os-$FLAVOR-$TAG.img IMAGE=quay.io/c3os/c3os:$FLAVOR-$TAG bash build.sh all-arm
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.flavor }}-image
          path: build
          if-no-files-found: error
