name: Release

on: 
 push:
   tags:
     - v*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       include:
         - flavor: "opensuse"
#        - flavor: "ubuntu"
         - flavor: "fedora"
         - flavor: "alpine"
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Login to Quay Registry
        run: echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io
      - name: Build  🔧
        if: startsWith(github.ref, 'refs/tags/')
        env:
          FLAVOR: ${{ matrix.flavor }}
          IMAGE: quay.io/c3os/c3os:${{ matrix.flavor }}-latest
        run: |
          TAG=${GITHUB_REF##*/}
          ISO=c3os-$FLAVOR-$TAG IMAGE=quay.io/c3os/c3os:$FLAVOR-$TAG bash build.sh
          mkdir release
          mv *.iso release/
          mv *.sha256 release/
      - name: Push to quay
        if: startsWith(github.ref, 'refs/tags/')
        run: | 
          TAG=${GITHUB_REF##*/}
          docker push quay.io/c3os/c3os:${{ matrix.flavor }}-$TAG
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: release/
          GHR_PARALLELISM: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          mv release/*.iso ./
          mv release/*.sha256 ./
      - uses: actions/upload-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.iso.zip
          path: |
            *.iso
            *.sha256
          if-no-files-found: error


  build-vm-images:
    needs: build
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
       include:
         - flavor: "opensuse"
         - flavor: "alpine"
#         - flavor: "ubuntu"
         - flavor: "fedora"
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          brew install hudochenkov/sshpass/sshpass
          brew install qemu
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.iso.zip
      - run: |
              ls -liah
              iso=$(ls *.iso)
              sh build_vm.sh $iso
      - uses: actions/upload-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.qcow2.tar.xz
          path: |
            *.qcow2.tar.xz
      - uses: actions/upload-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.ova
          path: |
            *.ova
          if-no-files-found: error

  release-images:
    runs-on: ubuntu-latest
    needs: build-vm-images
    strategy:
      fail-fast: false
      matrix:
       include:
         - flavor: "opensuse"
         - flavor: "alpine"
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.qcow2.tar.xz
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.ova
      - run: |
              mkdir release
              mv *.qcow2.tar.xz release/
              mv *.ova release/
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: release/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_PARALLELISM: 1