name: Build image

on: 
 push:
   tags:
     - v*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       include:
         - flavor: "opensuse"
         - flavor: "alpine"
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Login to Quay Registry
        run: echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io
      - name: Build  🔧
        if: startsWith(github.ref, 'refs/tags/')
        env:
          FLAVOR: ${{ matrix.flavor }}
          IMAGE: quay.io/mudler/c3os:${{ matrix.flavor }}-latest
        run: |
          TAG=${GITHUB_REF##*/}
          ISO=c3os-$FLAVOR-$TAG IMAGE=quay.io/mudler/c3os:$FLAVOR-$TAG bash build.sh
          mkdir release
          mv *.iso release/
          mv *.sha256 release/
      - name: Push to quay
        if: startsWith(github.ref, 'refs/tags/')
        run: | 
          TAG=${GITHUB_REF##*/}
          docker push quay.io/mudler/c3os:${{ matrix.flavor }}-$TAG
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: release/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}