name: Unit tests
on:
  pull_request:
  push:
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --skip-validate --snapshot
      - name: Run tests
        run: |
          ./earthly +test
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.out
      - uses: actions/upload-artifact@v2
        with:
          name: build.zip
          path: |
            dist/*