name: "Branding"
stages:
   initramfs:
     - name: "Branding"
       hostname: "c3os"
     - name: "Default systemd config"
       systemd:
        enable:
        - multi-user.target
        - getty@tty1
        - iscsid
        - systemd-timesyncd
        - nohang
        - nohang-desktop
        - sshd
        mask:
        - purge-kernels
       commands:
       - systemctl set-default multi-user.target
