name: "Branding"
stages:
   boot:
   - name: "Default sysctl settings"
     sysctl:
       net.core.rmem_max: 2500000
       vm.max_map_count: 262144
   initramfs:
     - name: "openRC setup"
       if: '[ -e "/sbin/openrc" ]'
       commands:
       - |
          rc-update add sshd boot
          rc-update add connman boot
          rc-update add acpid boot
          rc-update add hwclock boot
          rc-update add syslog boot
          rc-update add udev sysinit
          rc-update add udev-trigger sysinit
          rc-update add openntpd boot
          rc-update add crond
          rc-update add fail2ban

          mkdir -p /etc/runlevels/default
          ln -sf /etc/init.d/cos-setup-boot /etc/runlevels/default/cos-setup-boot
          ln -sf /etc/init.d/cos-setup-network /etc/runlevels/default/cos-setup-network
          ln -sf /etc/init.d/cos-setup-reconcile /etc/runlevels/default/cos-setup-reconcile
          ln -sf /etc/init.d/c3os-agent /etc/runlevels/default/c3os-agent
     - name: "Default systemd config"
       if: '[ -e "/sbin/systemctl" ] || [ -e "/usr/bin/systemctl" ] || [ -e "/usr/sbin/systemctl" ] || [ -e "/usr/bin/systemctl" ]'
       systemctl:
        enable:
        - multi-user.target
        - getty@tty1
        - iscsid
        - systemd-timesyncd
        - nohang
        - nohang-desktop
        - fail2ban
        - logrotate.timer
        - sshd
        mask:
        - purge-kernels
       commands:
       - systemctl set-default multi-user.target
