name: "Start recovery on tty1"
stages:
    initramfs:
     - name: "Starts c3os-recovery and generate a temporary pass"
       if: |
         cat /proc/cmdline | grep -q "vpnrecoverymode"
       commands:
       - systemctl disable getty@tty1
       - systemctl enable c3os-recovery
       - echo $RANDOM > /run/recovery_pass
       - echo c3os:$(cat /run/recovery_pass) | chpasswd 
       - |
          echo "Recovery mode. login with: c3os:$(cat /run/recovery_pass)" >> /etc/issue.d/02-login
    # Starts installer on boot in Alpine and openRC based
     - name: "Starts c3os-recovery with openRC-based systems"
       if: |
         [ -f "/etc/inittab" ] && \
         ( cat /proc/cmdline | grep -q "vpnrecoverymode" )
       commands:
       - sed -i -e 's/tty1.*//g' /etc/inittab
       - echo "tty1::respawn:/usr/bin/c3os recovery" >> /etc/inittab