name: "Additional grub menu entries"
stages:
    after-install:
    - name: "Mount state"
      commands:
      - |
          STATEDIR=/tmp/mnt/STATE
          STATE=$(blkid -L COS_STATE || true)
          mkdir -p $STATEDIR || true
          mount ${STATE} $STATEDIR
    - name: "Add grubmenu"
      files:
       - path: "/tmp/mnt/STATE/grubmenu"
         owner: 0
         group: 0
         permsisions: 0600
         content: |
            menuentry "c3os remote recovery" --id remoterecovery {
              if search.file /cOS/recovery.squashfs ; then
                set img=/cOS/recovery.squashfs
                set recoverylabel=COS_RECOVERY
              else
                set img=/cOS/recovery.img
              fi
              search.fs_label COS_RECOVERY root
              set label=COS_SYSTEM
              loopback loop0 /$img
              set root=($root)
              source (loop0)/etc/cos/bootargs.cfg
              linux (loop0)$kernel $kernelcmd ${extra_cmdline} ${extra_recovery_cmdline} vga=795 nomodeset c3os.remote_recovery_mode
              initrd (loop0)$initramfs
            }
    - name: "umount state"
      commands:
      - |
          umount /tmp/mnt/STATE